### PR TITLE
Added clean-jsdoc-theme

### PR DESCRIPTION
**Pull request by ankitskvmdam**
clean-jsdoc-theme is a template for JSDoc. To know more visit: https://www.npmjs.com/package/clean-jsdoc-theme

Screenshots of docs:
agentscript-code
agentscript-search
agentscript-dark

agentscript-home

### CODE REVIEW

**Comment by backspaces** [comment]
Hi! Thank you for the PR.

And indeed, I've already got an off-line version for clean-jsdoc-theme. It's a great theme. But..

Here's the story:
- We (@redfish) started out with documentation.js which had a feature we liked: the navigation panel could be layed out by topic. So all the Model modules could be seperate from the View models etc.

- But we ran into other issues such as documentation.js not following the jsDoc semantics closely, and also the repo is is no longer maintained.

- So we decided to use jsDoc, it's the Standard, and one of their themes, but decided to stay with vanilla jsDoc until we could evaluate several of them

- clean-jsdoc-theme is currently our favorite, but it does lack the control over the navigation panel layout. It also would be great if we could have a button switching between dark and light.

- And it also has to fit in nicely with our IDE that we've started on: https://agentscript.org/

.. So for now we'll stick with the Vanilla jsDoc

**Comment by ankitskvmdam** [comment]
Hi @backspaces, I am glad that `clean-jsdoc-theme` is your favourite. There are a lot of changes in the v4.x.x see: https://github.com/ankitskvmdam/clean-jsdoc-theme/blob/master/CHANGELOG.md#in-version-400

Now, in `clean-jsdoc-theme` there is a button at the top of the navigation bar, which you can use to toggle between dark and light themes. Visit: https://ankdev.me/clean-jsdoc-theme/v4/ to view it in action.

Screenshot:
image

It would be nice if you create a feature request issue for the navigation panel layout here: https://github.com/ankitskvmdam/clean-jsdoc-theme/issues. We will try to implement those as soon as possible.

And probably there will be no issue in fitting it with the IDE.

**Comment by backspaces** [comment]
WAY cool! Did your PR include the light/dark button? If not, could you do
so, I'll merge it in.

I think that puts us over the edge, we'll go for clean-jsDoc. And yes, I'll
submit an issue to the repo.

Thanks!

**Comment by ankitskvmdam** [comment]
Yes, it includes the light/dark button. 

And submitting an issue will be awesome.

And as we know, no library is perfect, so if you find any bug/issue, feel free to create an issue, I will try to solve it as soon as possible.

**Review by backspaces — COMMENTED** [review]
Looks just right, thanks.

**Review by backspaces — APPROVED** [review]
Looks fine, thanks

**Comment by backspaces** [comment]
I've got a simple problem I hope!

Before putting the README in the jsDoc/clean-jsdoc, I accessed it via github which converts .md to .html and also styles it as well. And not only for the main README, but the README's linked to.

But now the README is also in jsDoc which does fine for the main README, but not the linked-to README's. So for example, all my demo dirs (views1/, views2/, etc) have a simple README to run the demos. Looks like this: 

> https://github.com/backspaces/agentscript/blob/master/views1/README.md
> https://github.com/backspaces/agentscript/blob/master/views2/README.md

etc.

Is there a way to use jsDoc, or clean-jsdoc to do the conversion? I was looking at

> https://jsdoc.app/about-including-readme.html

for example. Not sure it could be done to the individual demo dirs.

**Comment by backspaces** [comment]
Maybe this: https://github.com/KrauseFx/markdown-to-html-github-style

Or similar.

**Comment by ankitskvmdam** [comment]
I think we can use JSDoc's tutorials config for this, https://jsdoc.app/about-tutorials.html

Also, we need to write a script to copy all the readme files to one directory called `tutorials`.

I will create a PR with these changes and then you can review it.

**Pull request merged**
