### PR TITLE
ask agents [consider yourselves turtles forevermore]

### PR DESCRIPTION
**Pull request by bennlich**
Turtles are finally upon us! Hoorah!

Resolves https://github.com/backspaces/agentscript/issues/47

I was pretty careful about my find/replace, but I may have missed certain compound names. I got:
* turtlesHere
* cacheTurtlesHere
* turtlesOnRect
* turtlesOnPatch
* turtlesOf
* refreshTurtles

The example models all run fine though!

This is definitely a breaking change. If we merge this, you'll need to replace all instances of `@agents` with `@turtles` (and maybe other less common things like the above-mentioned functions).

Going to go through the sketches and extras next.

### CODE REVIEW

**Comment by stephenguerin** [comment]
:-)  ! ! ! !

--- -. .   ..-. .. ... ....   - .-- ---   ..-. .. ... ....
Stephen.Guerin@Redfish.com
1600 Lena St #D1, Santa Fe, NM 87505
office: (505) 995-0206  mobile: (505) 577-5828
tw: @redfishgroup  skype: redfishgroup
redfish.com  |  simtable.com

**Comment by bennlich** [comment]
Okay, @backspaces . Lemme know what you think. I think it's ready.

**Comment by backspaces** [comment]
​Commit!​

**Comment by backspaces** [comment]
Did you run into difficulties?  Didn't see the merge yet.  I'll hold off
'till you're done.  Hope no conflicts.

   -- Owen

**Comment by backspaces** [comment]
.. or were you thinking I should?  Its a green button merge which is kinda nice.

**Comment by bennlich** [comment]
Merged! Should maybe send an e-mail out to the group about this? Or maybe we should pick a few things for a version 1.0, then tag it.

**Comment by bennlich** [comment]
> .. or were you thinking I should? Its a green button merge which is kinda nice.

When I work with @mariusnita, we usually let the reviewer do the merge. This guarantees that someone else has looked at the code.

**Comment by backspaces** [comment]
​Ah, team programming sort of thing.  Good idea but a lota work, right?

But, a miracle just occurred.  I successfully locally committed my own
changes, thus a clean working dir but ​naturally divergent from github:

On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working directory clean


So cool, I've got my local master up to date with a clean working dir.  I
did not add any of the derived files, even lib/  I did have to undo some
adds that occurred by doing a "gulp all" rather than a "gulp build".  Git
said to just do:
    use "git checkout -- <file>..." to discard changes in working directory
.. worked like a charm.

So I figured I could then pull from github and see if there were
conflicts.  Holy Cow, it worked!  Even managed the file name changes etc.
 40 files!

This is magic.

[image: Inline image 1]

**Comment by mariusnita** [comment]
> ​Ah, team programming sort of thing.  Good idea but a lota work, right?

It's actually easier I think. We're reviewing each other's code before it gets merged, so we're always up to speed. And we always have a chance to discuss design issues and improve the code before it gets merged.

**Comment by m0ose** [comment]
This is how I feel going into a code review. http://xkcd.com/1513/

**Comment by bennlich** [comment]
> It's actually easier I think. We're reviewing each other's code before it gets merged, so we're always up to speed. And we always have a chance to discuss design issues and improve the code before it gets merged.

The always up to speed part is important and oft overlooked, I think. Imagine if I'd merged this turtle branch without telling anyone =P

PRs are also a good place to explain how to use new things introduced in the changes. For example, your color module could maybe have benefited from a PR with a description briefly explaining all the new features and when/why to use them.

**Pull request merged**
