### PR TITLE
oops missing reduce starting val

### PR DESCRIPTION
**Pull request by bennlich**

### CODE REVIEW

**Comment by backspaces** [comment]
Makes sense, empty arrays return 0. But maybe better would be to check for empty and either throw an error or return null or nan +/- infinity.

But throwing is likely silly and 0 seems reasonable

**Comment by backspaces** [comment]
Whoa, just thought a bit about it. Having min start at 0 is likely a problem, right? Maybe min should start at +Infinity and max at -Infinity.
... and with a warning.

**Comment by backspaces** [comment]
I just switched to this:

```
    min(key) {
        return this.reduce(
            (prev, o) => Math.min(prev, key ? o[key] : o),
            Infinity
        )
    }
    max(key) {
        return this.reduce(
            (prev, o) => Math.max(prev, key ? o[key] : o),
            -Infinity
        )
    }
```

What do you think?

**Comment by bennlich** [comment]
Nice! Good catch.

**Pull request merged**
