### PR TITLE
Add tutorials

### PR DESCRIPTION
**Pull request by ankitskvmdam**
## Changes

1. Updated `clean-jsdoc-theme` from `v4.1.3` -> `v4.1.4`
2. Add a script to copy tutorials (README.md) from views2, views3, views3d, gis, ide-examples, mvc to the `tutorials` directory. This script will also create a tutorials.json file that contains information related to tutorials.
3. Update `build-docs` script in `package.json`. Previous `"build-docs": "jsdoc -c config/jsdoc.js"`, now: `"build-docs": "node copyTutorials.js && jsdoc -c config/jsdoc.js"`

Screenshots:
tutorial

In the next release of `clean-jsdoc-theme`, I will try to add a feature that will allow developers to rename the sidebar section's names. So that instead of calling it `Tutorials`, we can rename it to `Demos`.

### CODE REVIEW

**Review by backspaces — APPROVED** [review]
Looks great! We may want to move copyTutorials.js to docs/scripts or similar? 

Minor point if it complicates things.

**Comment by backspaces** [comment]
We have a go!

**Comment by backspaces** [comment]
Alas, when I try to merge the PR, I get a huge number of conflicts that github wants me to fix by hand!
They are all docs/ files, nothing in other parts of the repo.

I tried simply deleting the docs/ dir and github was still upset!
I finally reverted to commit/6727c2c so it should be as it was when you made the PR

Clearly my git/github fu is lacking!

Any ideas?

**Comment by ankitskvmdam** [comment]
Actually, it was my fault, I could have pulled all the latest changes from the origin.  I resolved all the conflicts and pushed the changes.


`copyTutorials.js` is more related to the dev step. The purpose of that script is to copy all the readme files into the tutorials folder. I'm not sure, maybe we can create a new folder called `dev` and move it into that folder or we can move it into config (just a thought).

**Pull request merged**
